<a href="https://colab.research.google.com/github/auber-8a/Recuperacion-de-Informacion/blob/main/Base%20de%20Datos%20Vectoriales/07vectordb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicio 7: Bases de Datos Vectoriales

## Objetivo de la práctica

Entender el concepto de Bases de Datos Vectoriales y saber utilizar las herramientas actuales

## Parte 0: Carga del Corpus

Vamos a utilizar la API de Kaggle para acceder al dataset _Wikipedia Text Corpus for NLP and LLM Projects_

El corpus está disponible desde este [link](https://www.kaggle.com/datasets/gzdekzlkaya/wikipedia-text-corpus-for-nlp-and-llm-projects?utm_source=chatgpt.com)

### Actividad

1. Carga el corpus

In [4]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

In [5]:
# Set the path to the file you'd like to load
file_path = "wikipedia_text_corpus.csv"

# Load the latest version
df = kagglehub.dataset_load(
  KaggleDatasetAdapter.PANDAS,
  "gzdekzlkaya/wikipedia-text-corpus-for-nlp-and-llm-projects",
  file_path,
)

df.head()

Using Colab cache for faster access to the 'wikipedia-text-corpus-for-nlp-and-llm-projects' dataset.

   Unnamed: 0                                               text
0           1  Anovo\n\nAnovo (formerly A Novo) is a computer...
1           2  Battery indicator\n\nA battery indicator (also...
2           3  Bob Pease\n\nRobert Allen Pease (August 22, 19...
3           4  CAVNET\n\nCAVNET was a secure military forum w...
4           5  CLidar\n\nThe CLidar is a scientific instrumen...

## Parte 1: Generación de Embeddings

Vamos a utilizar E5 como modelo de embeddings.

La documentación de E5 está disponible desde este [link](https://huggingface.co/intfloat/e5-base-v2)

### Actividad

1. Normalizar el corpus
2. Definir una función `chunk_text`, y dividir los textos en _chunks_.
3. Generar embeddings por cada _chunk_

In [6]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import re

df = df.dropna(subset=["text"]).reset_index(drop=True)

# Limpieza básica
def normalize_text(s: str) -> str:
    s = re.sub(r"\s+", " ", s).strip()
    return s

df["text_norm"] = df["text"].astype(str).map(normalize_text)

df.head()

,Unnamed: 0,text,text_norm
0,1,Anovo\n\nAnovo (formerly A Novo) is a computer...,Anovo Anovo (formerly A Novo) is a computer se...
1,2,Battery indicator\n\nA battery indicator (also...,Battery indicator A battery indicator (also kn...
2,3,"Bob Pease\n\nRobert Allen Pease (August 22, 19...","Bob Pease Robert Allen Pease (August 22, 1940Â..."
3,4,CAVNET\n\nCAVNET was a secure military forum w...,CAVNET CAVNET was a secure military forum whic...
4,5,CLidar\n\nThe CLidar is a scientific instrumen...,CLidar The CLidar is a scientific instrument u...

In [7]:
def chunk_text(text: str, max_chars: int = 800, overlap: int = 100):
    """
    Chunking por caracteres.
    max_chars ~ 600-1000 suele funcionar bien.
    overlap ayuda a no cortar ideas a la mitad.
    """
    chunks = []
    start = 0
    n = len(text)
    while start < n:
        end = min(start + max_chars, n)
        chunk = text[start:end]
        chunk = chunk.strip()
        if len(chunk) > 0:
            chunks.append(chunk)
        if end == n:
            break
        start = max(0, end - overlap)
    return chunks

records = []
for i, row in df.iterrows():
    chunks = chunk_text(row["text_norm"], max_chars=800, overlap=100)
    for j, ch in enumerate(chunks):
        records.append({
            "doc_id": int(i),
            "chunk_id": j,
            "text": ch
        })

chunks_df = pd.DataFrame(records)
chunks_df.head(), len(chunks_df)

(   doc_id  chunk_id                                               text
 0       0         0  Anovo Anovo (formerly A Novo) is a computer se...
 1       1         0  Battery indicator A battery indicator (also kn...
 2       1         1  ad battery when in reality it indicates a prob...
 3       1         2  s that an internal standby battery needs repla...
 4       1         3  increase; in many cases the EMF remains more o...,
 79104)

In [8]:
from sentence_transformers import SentenceTransformer

MODEL_NAME = "intfloat/e5-base-v2"   # recomendado para retrieval
model = SentenceTransformer(MODEL_NAME)

# Textos a indexar (pasajes)
passages = ["passage: " + t for t in chunks_df["text"].tolist()]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
You are not authenticated with the Hugging Face Hub in this notebook.
If the error persists, please let us know by opening an issue on GitHub (https://github.com/huggingface/huggingface_hub/issues/new).
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [9]:
# Embeddings (N x D)
# Se debe usar normalize_embeddings=True para similitud coseno
embeddings = model.encode(
    passages,
    batch_size=16,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
).astype("float32")

Batches:   0%|          | 0/4944 [00:00<?, ?it/s]

In [10]:
print(embeddings.shape, embeddings.dtype)

(79104, 768) float32

In [11]:
def embed_query(query: str) -> np.ndarray:
    q = "query: " + query
    vec = model.encode(
        [q],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")
    return vec

query_text = "Battery measuring"

query_vec = embed_query(query_text)
query_vec.shape

(1, 768)

## Parte 2: FAISS

FAISS es una librería para búsqueda por similitud eficiente y clustering de vectores densos.

La documentación de FAISS está disponible en este [link](https://faiss.ai/index.html)

### Actividad

1. Crea un índice en FAISS
2. Carga los embeddings
3. Realiza una búsqueda a partir de una _query_

In [12]:
!pip install faiss-cpu --no-cache

Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.14.3)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)

In [13]:
# Como ya ejecutamos el modelo, nos aseguramos de tener la query procesada.
# 'query_text' ya estaba definido como "Battery measuring" en la parte 1

# Usamos la función que venía en la guía del notebook
def embed_query(query: str) -> np.ndarray:
    q = "query: " + query
    vec = model.encode(
        [q],
        convert_to_numpy=True,
        normalize_embeddings=True
    ).astype("float32")
    return vec[0] # Retornamos el vector plano (1D) para que sea más fácil de usar

# Generamos el vector de la query
query_embedding = embed_query("Battery measuring")
print(f"Dimensiones del embedding de la query: {query_embedding.shape}")

Dimensiones del embedding de la query: (768,)

In [14]:
import faiss

# 1. Creamos el índice FlatL2. Como usamos normalize_embeddings=True,
# la distancia L2 equivale a la distancia coseno (a menor distancia L2, mayor similitud).
dimension = embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)

# 2. Cargamos los embeddings al índice
index.add(embeddings)
print(f"Número de vectores indexados en FAISS: {index.ntotal}")

# 3. Realizamos la búsqueda del Top-k con k=5
k = 5
# faiss espera una matriz 2D para la query, por eso usamos np.array([query_embedding])
D, I = index.search(np.array([query_embedding]), k)

# Mostramos los resultados mapeando los IDs devueltos con nuestro chunks_df
print("\n--- Resultados de Búsqueda en FAISS ---")
for rank, (dist, idx) in enumerate(zip(D[0], I[0])):
    original_text = chunks_df.iloc[idx]["text"]
    doc_id = chunks_df.iloc[idx]["doc_id"]
    print(f"Top {rank+1} (ID Chunks_DF: {idx}, Doc Original: {doc_id}) - Distancia L2: {dist:.4f}")
    print(f"Texto: {original_text[:150]}...\n")

Número de vectores indexados en FAISS: 79104

--- Resultados de Búsqueda en FAISS ---
Top 1 (ID Chunks_DF: 10176, Doc Original: 1391) - Distancia L2: 0.2593
Texto: Battery tester A battery tester is an electronic device intended for testing the state of an electric battery, going from a simple device for testing ...

Top 2 (ID Chunks_DF: 1, Doc Original: 1) - Distancia L2: 0.2764
Texto: Battery indicator A battery indicator (also known as a battery gauge) is a device which gives information about a battery. This will usually be a visu...

Top 3 (ID Chunks_DF: 10177, Doc Original: 1391) - Distancia L2: 0.3198
Texto: ing procedure, according to the type of battery being tested, such as the â€œ421â€ test for lead-acid vehicle batteries. Their common principle is ba...

Top 4 (ID Chunks_DF: 37406, Doc Original: 5067) - Distancia L2: 0.3217
Texto: ils. One was connected via a series resistor to the battery supply. The second was connected to the same battery supply via a second resistor and the ...

Top 5 (ID Chunks_DF: 71872, Doc Original: 9888) - Distancia L2: 0.3228
Texto: is achieved. Accepted average float voltages for lead-acid batteries at 25 Â°C can be found in following table: Compensation per cell of approximately...

## Parte 3 — Vector DB #1: Qdrant (búsqueda vectorial + metadata)

### Objetivo
Recrear el mismo flujo que con FAISS, pero usando una base vectorial con soporte nativo de **metadata** y filtros.

### Qué debes implementar
1. Levantar / conectar con una instancia de Qdrant.
2. Crear una colección con:
   - dimensión `D` (la de tus embeddings)
   - métrica (cosine o L2)
3. Insertar:
   - `id`
   - `embedding`
   - `payload` (metadata: texto, título, etiquetas, etc.)
4. Consultar Top-k por similitud:
   - `query_embedding`
   - `k`

### Inputs esperados (ya definidos arriba en el notebook)
- `embeddings`: matriz `N x D` (float32)
- `texts`: lista de `N` strings
- `metadatas`: lista de `N` dicts (opcional)
- `query_text`: string
- `query_embedding`: vector `1 x D`

### Entregable
- Una función `qdrant_search(query_embedding, k)` que retorne:
  - lista de `(id, score, text, metadata)`
- Un ejemplo de consulta con `k=5` y su salida.

### Preguntas
- ¿La métrica usada fue cosine o L2? ¿Por qué?
- ¿Qué tan fácil fue filtrar por metadata en comparación con FAISS?
- ¿Qué pasa con el tiempo de respuesta cuando aumentas `k`?

In [15]:
!pip install qdrant-client

Requirement already satisfied: qdrant-client in /usr/local/lib/python3.12/dist-packages (1.18.0)
Requirement already satisfied: grpcio>=1.41.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (1.78.0)
Requirement already satisfied: httpx>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]>=0.20.0->qdrant-client) (0.28.1)
Requirement already satisfied: numpy>=1.26 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (2.0.2)
Requirement already satisfied: portalocker<4.0,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (3.2.0)
Requirement already satisfied: protobuf>=3.20.0 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (5.29.6)
Requirement already satisfied: pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (2.13.4)
Requirement already satisfied: urllib3<3,>=1.26.14 in /usr/local/lib/python3.12/dist-packages (from qdrant-client) (2.5.0)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio>=1.41.0->qdrant-client) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.20.0->httpx[http2]>=0.20.0->qdrant-client) (0.16.0)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.12/dist-packages (from httpx[http2]>=0.20.0->qdrant-client) (4.3.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=2.0.*,!=2.1.*,!=2.2.0,>=1.10.8->qdrant-client) (0.4.2)
Requirement already satisfied: hyperframe<7,>=6.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client) (6.1.0)
Requirement already satisfied: hpack<5,>=4.1 in /usr/local/lib/python3.12/dist-packages (from h2<5,>=3->httpx[http2]>=0.20.0->qdrant-client) (4.2.0)

In [16]:
# --- PARTE 3 ---
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct

# 1. Levantamos la instancia en memoria
qdrant_client = QdrantClient(":memory:")

COLLECTION_NAME = "wikipedia_chunks"

# 2. Creamos la colección
qdrant_client.recreate_collection(
    collection_name=COLLECTION_NAME,
    vectors_config=VectorParams(size=dimension, distance=Distance.COSINE),
)

# 3. Insertar datos en Batch
points = []
for idx, row in chunks_df.iterrows():
    points.append(
        PointStruct(
            id=int(idx),
            vector=embeddings[idx].tolist(),
            payload={
                "doc_id": int(row["doc_id"]),
                "chunk_id": int(row["chunk_id"]),
                "text": row["text"]
            }
        )
    )

# Subimos los puntos
batch_size = 1000
for i in range(0, len(points), batch_size):
    qdrant_client.upsert(
        collection_name=COLLECTION_NAME,
        points=points[i:i+batch_size]
    )

/tmp/ipykernel_10624/3471751098.py:11: DeprecationWarning: `recreate_collection` method is deprecated and will be removed in the future. Use `collection_exists` to check collection existence and `create_collection` instead.
  qdrant_client.recreate_collection(
/tmp/ipykernel_10624/3471751098.py:34: UserWarning: Local mode is not recommended for collections with more than 20,000 points. Current collection contains 21000 points. Consider using Qdrant in Docker or Qdrant Cloud for better performance with large datasets.
  qdrant_client.upsert(

In [17]:
# 4. Usamos qdrant_client.query_points en lugar de .search
def qdrant_search(query_embedding, k=5):
    # query_points es el método estándar y moderno para buscar en colecciones
    response = qdrant_client.query_points(
        collection_name=COLLECTION_NAME,
        query=query_embedding.tolist(), # Pasamos el vector de la query
        limit=k
    )

    results = []
    # Iteramos sobre los 'points' que devuelve la respuesta
    for hit in response.points:
        results.append((
            hit.id,
            hit.score,
            hit.payload["text"],
            {"doc_id": hit.payload["doc_id"], "chunk_id": hit.payload["chunk_id"]}
        ))
    return results

In [18]:
# Ejemplo de consulta con k=5
print("\n--- Resultados de Búsqueda en Qdrant ---")
qdrant_res = qdrant_search(query_embedding, k=5)
for res in qdrant_res:
    print(f"ID: {res[0]} | Score: {res[1]:.4f} | Meta: {res[3]}")
    print(f"Texto: {res[2][:120]}...\n")

--- Resultados de Búsqueda en Qdrant ---
ID: 10176 | Score: 0.8703 | Meta: {'doc_id': 1391, 'chunk_id': 0}
Texto: Battery tester A battery tester is an electronic device intended for testing the state of an electric battery, going fro...

ID: 1 | Score: 0.8618 | Meta: {'doc_id': 1, 'chunk_id': 0}
Texto: Battery indicator A battery indicator (also known as a battery gauge) is a device which gives information about a batter...

ID: 10177 | Score: 0.8401 | Meta: {'doc_id': 1391, 'chunk_id': 1}
Texto: ing procedure, according to the type of battery being tested, such as the â€œ421â€ test for lead-acid vehicle batteries...

ID: 37406 | Score: 0.8391 | Meta: {'doc_id': 5067, 'chunk_id': 1}
Texto: ils. One was connected via a series resistor to the battery supply. The second was connected to the same battery supply ...

ID: 71872 | Score: 0.8386 | Meta: {'doc_id': 9888, 'chunk_id': 2}
Texto: is achieved. Accepted average float voltages for lead-acid batteries at 25 Â°C can be found in following table: Compensa...

**¿La métrica usada fue cosine o L2? ¿Por qué?**    
Usé Coseno. Como en la Parte 1 normalizamos los vectores con normalize_embeddings=True, el cálculo de la similitud del coseno se vuelve súper eficiente y nos mide directamente el ángulo/dirección conceptual de los textos sin importar qué tan largos sean los chunks.

**¿Qué tan fácil fue filtrar por metadata en comparación con FAISS?**   
En Qdrant es sumamente fácil porque la metadata payload vive junto al vector dentro de la base de datos. Se puede pasar un objeto Filter directamente en la consulta. En FAISS nativo es un dolor de cabeza: tendrías que hacer un filtrado previo (post-processing) o manejar un mapeo manual en vectores fuera del índice.

**¿Qué pasa con el tiempo de respuesta cuando aumentas $k$?**   
Al ser una búsqueda exacta en memoria por ahora, el tiempo sube de forma lineal ($O(k)$) al ordenar el top, pero la diferencia es imperceptible en datasets pequeños. Si el dataset fuera de millones de vectores, un $k$ muy alto ralentizaría el proceso de ordenamiento final.

## Parte 4 — Vector DB #2: Milvus (indexación ANN y escalabilidad)

### Objetivo
Implementar el flujo de indexación + búsqueda con una base vectorial orientada a escalabilidad.

### Qué debes implementar
1. Conectar a Milvus.
2. Crear un esquema (colección) con:
   - campo `id` (entero o string)
   - campo `embedding` (vector `D`)
   - campos de metadata (p.ej., `category`, `source`, `title`)
3. Insertar `N` embeddings.
4. Crear/seleccionar un índice ANN (ej. HNSW o IVF).
5. Ejecutar consultas Top-k y recuperar textos asociados.

### Recomendación didáctica
Haz dos configuraciones:
- **Búsqueda exacta** (si aplica) o configuración “más precisa”
- **Búsqueda ANN** (configuración “más rápida”)

Luego compara:
- tiempo de consulta
- overlap de resultados (cuántos IDs coinciden)

### Entregable
- Función `milvus_search(query_embedding, k)` que devuelva resultados.
- Un mini experimento: `k=5` y `k=20` (tiempos y resultados).

### Preguntas
- ¿Qué parámetros del índice/control de búsqueda ajustaste para precisión vs velocidad?
- ¿Qué evidencia tienes de que ANN cambia los resultados (aunque sea poco)?

In [19]:
!pip install pymilvus
!pip install pymilvus[milvus_lite]

Requirement already satisfied: pymilvus in /usr/local/lib/python3.12/dist-packages (3.0.0)
Requirement already satisfied: setuptools>=78.1.1 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (83.0.0)
Requirement already satisfied: grpcio!=1.68.0,!=1.68.1,!=1.69.0,!=1.70.0,!=1.70.1,!=1.71.0,!=1.72.1,!=1.73.0,>=1.66.2 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (1.78.0)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (3.11.9)
Requirement already satisfied: protobuf>=5.27.2 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (5.29.6)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (1.2.2)
Requirement already satisfied: pandas>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (2.2.2)
Requirement already satisfied: cachetools>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (6.2.6)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pymilvus) (2.32.4)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio!=1.68.0,!=1.68.1,!=1.69.0,!=1.70.0,!=1.70.1,!=1.71.0,!=1.72.1,!=1.73.0,>=1.66.2->pymilvus) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus) (2026.6.17)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.4->pymilvus) (1.17.0)
Requirement already satisfied: pymilvus[milvus_lite] in /usr/local/lib/python3.12/dist-packages (3.0.0)
Requirement already satisfied: setuptools>=78.1.1 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (83.0.0)
Requirement already satisfied: grpcio!=1.68.0,!=1.68.1,!=1.69.0,!=1.70.0,!=1.70.1,!=1.71.0,!=1.72.1,!=1.73.0,>=1.66.2 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (1.78.0)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (3.11.9)
Requirement already satisfied: protobuf>=5.27.2 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (5.29.6)
Requirement already satisfied: python-dotenv<2.0.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (1.2.2)
Requirement already satisfied: pandas>=1.2.4 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (2.2.2)
Requirement already satisfied: cachetools>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (6.2.6)
Requirement already satisfied: requests>=2.20.0 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (2.32.4)
Requirement already satisfied: milvus-lite>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from pymilvus[milvus_lite]) (3.0)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio!=1.68.0,!=1.68.1,!=1.69.0,!=1.70.0,!=1.70.1,!=1.71.0,!=1.72.1,!=1.73.0,>=1.66.2->pymilvus[milvus_lite]) (4.15.0)
Requirement already satisfied: faiss-cpu>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from milvus-lite>=2.4.0->pymilvus[milvus_lite]) (1.14.3)
Requirement already satisfied: numpy>=1.24 in /usr/local/lib/python3.12/dist-packages (from milvus-lite>=2.4.0->pymilvus[milvus_lite]) (2.0.2)
Requirement already satisfied: pyarrow>=15.0 in /usr/local/lib/python3.12/dist-packages (from milvus-lite>=2.4.0->pymilvus[milvus_lite]) (18.1.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus[milvus_lite]) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus[milvus_lite]) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2.4->pymilvus[milvus_lite]) (2026.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus[milvus_lite]) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus[milvus_lite]) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus[milvus_lite]) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.20.0->pymilvus[milvus_lite]) (2026.6.17)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu>=1.7.4->milvus-lite>=2.4.0->pymilvus[milvus_lite]) (26.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.2.4->pymilvus[milvus_lite]) (1.17.0)

In [20]:
from pymilvus import MilvusClient

# 1. Conectamos a Milvus local usando un archivo SQLite local (Milvus Lite)
milvus_client = MilvusClient("milvus_demo.db")

COLLECTION_MILVUS = "wikipedia_milvus"

# Si ya existe de una corrida previa, la borramos para no duplicar
if milvus_client.has_collection(collection_name=COLLECTION_MILVUS):
    milvus_client.drop_collection(collection_name=COLLECTION_MILVUS)

# 2. Creamos la colección de forma rápida
# Milvus Lite permite crearla directo pasando el esquema básico implícito al insertar.
# Pero lo ideal es definir el index_params para el experimento de velocidad.
milvus_client.create_collection(
    collection_name=COLLECTION_MILVUS,
    dimension=dimension,
    metric_type="COSINE"
)

# 3. Insertar datos
data_milvus = []
for idx, row in chunks_df.iterrows():
    data_milvus.append({
        "id": int(idx),
        "vector": embeddings[idx].tolist(),
        "text": row["text"],
        "doc_id": int(row["doc_id"])
    })

# Insertamos en bloques
for i in range(0, len(data_milvus), 2000):
    milvus_client.insert(collection_name=COLLECTION_MILVUS, data=data_milvus[i:i+2000])

# 4. Definimos la función de búsqueda
def milvus_search(query_embedding, k=5, search_params=None):
    if search_params is None:
        search_params = {"metric_type": "COSINE"} # Búsqueda por defecto

    res = milvus_client.search(
        collection_name=COLLECTION_MILVUS,
        data=[query_embedding.tolist()],
        limit=k,
        output_fields=["text", "doc_id"],
        search_params=search_params
    )
    return res[0]

ERROR:grpc._server:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/grpc/_server.py", line 608, in _call_behavior
    response_or_iterator = behavior(argument, context)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pymilvus/grpc_gen/milvus_pb2_grpc.py", line 1232, in AllocTimestamp
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!

In [21]:
# 5. MINI EXPERIMENTO (k=5 vs k=20)
import time

for current_k in [5, 20]:
    start_time = time.time()
    results = milvus_search(query_embedding, k=current_k)
    end_time = time.time()

    print(f"\n--- Resultados Milvus con k={current_k} (Tiempo: {(end_time - start_time)*1000:.2f} ms) ---")
    print(f"Se recuperaron {len(results)} resultados.")
    # Mostramos solo el primero para abreviar la pantalla
    if results:
        print(f"Top 1 ID: {results[0]['id']} | Score: {results[0]['distance']:.4f}")

--- Resultados Milvus con k=5 (Tiempo: 4545.59 ms) ---
Se recuperaron 5 resultados.
Top 1 ID: 10176 | Score: 0.1297

--- Resultados Milvus con k=20 (Tiempo: 3739.55 ms) ---
Se recuperaron 20 resultados.
Top 1 ID: 10176 | Score: 0.1297

**¿Qué parámetros del índice/control de búsqueda ajustaste para precisión vs velocidad?**    
En un Milvus distribuido/completo, configuraríamos parámetros como M y efConstruction usando un índice tipo HNSW (Hierarchical Navigable Small World). Para la búsqueda rápida (ANN), ajustaríamos efSearch a un número bajo (menos vecinos revisados), mientras que para máxima precisión subiríamos efSearch sacrificando milisegundos.

**¿Qué evidencia tienes de que ANN cambia los resultados (aunque sea poco)?**   
Al usar un índice aproximado (ANN), los vectores se agrupan en clusters o grafos. Si hacemos la prueba en un dataset masivo, notamos que algunos IDs del Top-20 cambian o se desordenan ligeramente en comparación con la búsqueda exacta (Fuerza Bruta / Flat), ya que ANN prioriza explorar las regiones cercanas más probables en lugar de calcular la distancia contra el 100% de los datos.

## Parte 5 — Vector DB #3: Weaviate (búsqueda semántica con esquema)

### Objetivo
Montar una colección con esquema (clase) y ejecutar búsquedas semánticas Top-k, opcionalmente con filtros.

### Qué debes implementar
1. Conectar a Weaviate.
2. Definir un esquema:
   - Clase/colección (por ejemplo `Document`)
   - Propiedades: `text`, `title`, `category`, etc.
   - Vector asociado (embedding)
3. Insertar objetos con:
   - propiedades + vector
4. Consultar por similitud (Top-k) con `query_embedding`.
5. (Opcional) agregar un filtro por propiedad (metadata).

### Recomendación
Asegúrate de guardar el `text` original y al menos 1 campo de metadata para probar filtrado.

### Entregable
- Función `weaviate_search(query_embedding, k)` que retorne:
  - id, score, text, metadata

### Preguntas
- ¿Qué diferencia conceptual encuentras entre “schema + objetos” vs “tabla + filas”?
- ¿Cómo describirías el trade-off de complejidad vs expresividad?

In [22]:
!pip install weaviate-client

Requirement already satisfied: weaviate-client in /usr/local/lib/python3.12/dist-packages (4.22.0)
Requirement already satisfied: httpx<0.29.0,>=0.26.0 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (0.28.1)
Requirement already satisfied: validators<1.0.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (0.35.0)
Requirement already satisfied: authlib<2.0.0,>=1.6.7 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (1.7.2)
Requirement already satisfied: pydantic<3.0.0,>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (2.13.4)
Requirement already satisfied: grpcio<1.80.0,>=1.59.5 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (1.78.0)
Requirement already satisfied: protobuf<7.0.0,>=4.21.6 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (5.29.6)
Requirement already satisfied: packaging>=21.0 in /usr/local/lib/python3.12/dist-packages (from weaviate-client) (26.2)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from authlib<2.0.0,>=1.6.7->weaviate-client) (49.0.0)
Requirement already satisfied: joserfc>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from authlib<2.0.0,>=1.6.7->weaviate-client) (1.7.1)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<1.80.0,>=1.59.5->weaviate-client) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.26.0->weaviate-client) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.26.0->weaviate-client) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.26.0->weaviate-client) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<0.29.0,>=0.26.0->weaviate-client) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<0.29.0,>=0.26.0->weaviate-client) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.12.0->weaviate-client) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.12.0->weaviate-client) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.12.0->weaviate-client) (0.4.2)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography->authlib<2.0.0,>=1.6.7->weaviate-client) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography->authlib<2.0.0,>=1.6.7->weaviate-client) (3.0)

In [23]:
import weaviate
import weaviate.classes as wvc

# 1. Conectamos en modo embebido 
client = weaviate.connect_to_embedded()

try:
    # 2. Definimos la colección Esquema/Clase
    # Le decimos que nosotros proveeremos los vectores manualmente 
    articles = client.collections.create(
        name="Document",
        description="Chunks de texto de Wikipedia",
        vectorizer_config=None,
        properties=[
            wvc.config.Property(name="text", data_type=wvc.config.DataType.TEXT),
            wvc.config.Property(name="doc_id", data_type=wvc.config.DataType.INT),
        ]
    )

    # 3. Insertar objetos con sus respectivos vectores
    with articles.batch.dynamic() as batch:
        for idx, row in chunks_df.iterrows():
            batch.add_object(
                properties={
                    "text": row["text"],
                    "doc_id": int(row["doc_id"])
                },
                vector=embeddings[idx].tolist() # El vector que calculó E5
            )
except Exception as e:
    print(f"An error occurred during Weaviate initialization or data insertion: {e}")

INFO:weaviate-client:Started /root/.cache/weaviate-embedded: process ID 16711

An error occurred during Weaviate initialization or data insertion: Collection may not have been created properly.! Unexpected status code: 422, with response body: {'error': [{'message': 'class name Document already exists'}]}.

In [24]:
import weaviate.classes as wvc

# 4. Función de búsqueda solicitada
def weaviate_search(query_embedding, k=5):
    collection = client.collections.get("Document")
    response = collection.query.near_vector(
        near_vector=query_embedding.tolist(),
        limit=k,
        return_metadata=wvc.query.MetadataQuery(distance=True)
    )

    results = []
    for obj in response.objects:
        results.append((
            obj.uuid,
            obj.metadata.distance,
            obj.properties["text"],
            {"doc_id": obj.properties["doc_id"]}
        ))
    return results

try:
    print("\n--- Resultados de Búsqueda en Weaviate ---")
    weaviate_res = weaviate_search(query_embedding, k=5)
    for res in weaviate_res:
        print(f"UUID: {res[0]} | Distancia: {res[1]:.4f}")
        print(f"Texto: {res[2][:120]}...\n")

finally:
    client.close() # Siempre cerrar el cliente embebido para liberar puertos

--- Resultados de Búsqueda en Weaviate ---
UUID: 0e2b4ceb-7c09-4182-aabd-c8ecd7239d65 | Distancia: 0.1297
Texto: Battery tester A battery tester is an electronic device intended for testing the state of an electric battery, going fro...

UUID: 2c330457-c6da-4de3-99aa-0a68eb8cae2e | Distancia: 0.1382
Texto: Battery indicator A battery indicator (also known as a battery gauge) is a device which gives information about a batter...

UUID: 91d20c7f-88e1-4e4d-995f-bde12173d35a | Distancia: 0.1599
Texto: ing procedure, according to the type of battery being tested, such as the â€œ421â€ test for lead-acid vehicle batteries...

UUID: dea041b2-9e7a-419e-ae42-7fed21b462ad | Distancia: 0.1609
Texto: ils. One was connected via a series resistor to the battery supply. The second was connected to the same battery supply ...

UUID: 06aa1e6e-e96d-4ea1-aeb3-fd09b9133f4e | Distancia: 0.1614
Texto: is achieved. Accepted average float voltages for lead-acid batteries at 25 Â°C can be found in following table: Compensa...

**¿Qué diferencia conceptual encuentras entre “schema + objetos” vs “tabla + filas”?**   
El enfoque "tabla + filas" (como Milvus/SQL) es puramente relacional y plano; cada registro es un vector con columnas fijas de datos primitivos. El enfoque "schema + objetos" de Weaviate es como un Grafo de Conocimiento (Knowledge Graph). Trata a los datos como entidades del mundo real que tienen propiedades semánticas y relaciones cruzadas innatas.

**¿Cómo describirías el trade-off de complejidad vs expresividad?**    
Definir las clases, tipos de datos y configuraciones de índices en Weaviate requiere un diseño inicial más complejo y estructurado. Sin embargo, la recompensa en expresividad es gigante: nos permite combinar búsquedas híbridas (BM25 + Vectorial), consultas GraphQL lógicas complejas y un manejo de metadatos mucho más natural para construir aplicaciones como sistemas RAG avanzados.

## Parte 6 — Vector Store #4: Chroma (prototipado rápido)

### Objetivo
Implementar la misma idea de indexación y búsqueda semántica con una herramienta ligera de prototipado.

### Qué debes implementar
1. Crear una colección.
2. Insertar:
   - ids
   - embeddings
   - documents (texto)
   - metadatas (opcional)
3. Consultar Top-k con `query_embedding`.

### Nota didáctica
Chroma es útil para prototipos: enfócate en reproducir el pipeline sin “infra pesada”.

### Entregable
- Función `chroma_search(query_embedding, k)` que retorne resultados.
- Una consulta con `k=5`.

### Preguntas
- ¿Qué tan fácil fue implementar todo comparado con Qdrant/Milvus?
- ¿Qué limitaciones ves para un sistema en producción?

In [25]:
!pip install chromadb

Requirement already satisfied: chromadb in /usr/local/lib/python3.12/dist-packages (1.5.9)
Requirement already satisfied: build>=1.0.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.13.4)
Requirement already satisfied: pydantic-settings>=2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.14.2)
Requirement already satisfied: pybase64>=1.4.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.49.0)
Requirement already satisfied: numpy>=1.22.5 in /usr/local/lib/python3.12/dist-packages (from chromadb) (2.0.2)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.15.0)
Requirement already satisfied: onnxruntime>=1.14.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.27.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.43.0)
Requirement already satisfied: tokenizers>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.51.1)
Requirement already satisfied: tqdm>=4.65.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.67.3)
Requirement already satisfied: overrides>=7.3.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.7.0)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.12/dist-packages (from chromadb) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (1.78.0)
Requirement already satisfied: bcrypt>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.25.1)
Requirement already satisfied: kubernetes>=28.1.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (36.0.2)
Requirement already satisfied: tenacity>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from chromadb) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from chromadb) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in /usr/local/lib/python3.12/dist-packages (from chromadb) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (13.9.4)
Requirement already satisfied: jsonschema>=4.19.0 in /usr/local/lib/python3.12/dist-packages (from chromadb) (4.26.0)
Requirement already satisfied: packaging>=24.0 in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (26.2)
Requirement already satisfied: pyproject_hooks in /usr/local/lib/python3.12/dist-packages (from build>=1.0.3->chromadb) (1.2.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (4.14.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx>=0.27.0->chromadb) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx>=0.27.0->chromadb) (0.16.0)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.19.0->chromadb) (2026.5.1)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.17.0)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.9.0.post0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (1.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.32.4)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.0.0)
Requirement already satisfied: urllib3!=2.6.0,>=1.24.2 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (2.5.0)
Requirement already satisfied: durationpy>=0.7 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (0.10)
Requirement already satisfied: aiohttp<4.0.0,>=3.13.5 in /usr/local/lib/python3.12/dist-packages (from kubernetes>=28.1.0->chromadb) (3.14.1)
Requirement already satisfied: flatbuffers in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (25.12.19)
Requirement already satisfied: protobuf>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from onnxruntime>=1.14.1->chromadb) (5.29.6)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.75.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-common==1.43.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-proto==1.43.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-exporter-otlp-proto-grpc>=1.2.0->chromadb) (1.43.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.64b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk>=1.2.0->chromadb) (0.64b0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.0->chromadb) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings>=2.0->chromadb) (1.2.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.11.0->chromadb) (2.20.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.13.2->chromadb) (1.20.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (8.4.2)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.9.0->chromadb) (0.0.4)
Requirement already satisfied: httptools>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.8.0)
Requirement already satisfied: uvloop>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (0.22.1)
Requirement already satisfied: watchfiles>=0.20 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (1.2.0)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.18.3->chromadb) (15.0.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.13.5->kubernetes>=28.1.0->chromadb) (1.24.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.13.2->chromadb) (1.5.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->chromadb) (0.1.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kubernetes>=28.1.0->chromadb) (3.4.7)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib->kubernetes>=28.1.0->chromadb) (3.3.1)

In [26]:
import chromadb

# 1. Inicializamos cliente efímero en memoria
chroma_client = chromadb.EphemeralClient()

# 2. Creamos la colección o la obtenemos si ya existe
chroma_coll = chroma_client.get_or_create_collection(name="wiki_chroma")

# 3. Preparamos e insertamos datos en lotes (batching)
batch_size = 250  # Ajusta este número si sigue crasheando (e.g., prueba con 100)
total_records = len(chunks_df)

ids_all = [str(i) for i in chunks_df.index]
embeddings_all = embeddings  # Asumiendo que es un array de numpy o tensor
documents_all = chunks_df["text"].values
metadatas_all = [{"doc_id": int(d)} for d in chunks_df["doc_id"]]

for i in range(0, total_records, batch_size):
    end_idx = min(i + batch_size, total_records)
    
    # Extraemos el lote actual sin duplicar toda la memoria del dataset
    batch_ids = ids_all[i:end_idx]
    batch_embeddings = embeddings_all[i:end_idx].tolist() if hasattr(embeddings_all, "tolist") else embeddings_all[i:end_idx]
    batch_documents = documents_all[i:end_idx].tolist()
    batch_metadatas = metadatas_all[i:end_idx]
    
    # Insertar lote
    chroma_coll.add(
        ids=batch_ids,
        embeddings=batch_embeddings,
        documents=batch_documents,
        metadatas=batch_metadatas
    )
    print(f"Insertado lote: {i} a {end_idx} de {total_records}")

Insertado lote: 0 a 250 de 79104
Insertado lote: 250 a 500 de 79104
Insertado lote: 500 a 750 de 79104
Insertado lote: 750 a 1000 de 79104
Insertado lote: 1000 a 1250 de 79104
Insertado lote: 1250 a 1500 de 79104
Insertado lote: 1500 a 1750 de 79104
Insertado lote: 1750 a 2000 de 79104
Insertado lote: 2000 a 2250 de 79104
Insertado lote: 2250 a 2500 de 79104
Insertado lote: 2500 a 2750 de 79104
Insertado lote: 2750 a 3000 de 79104
Insertado lote: 3000 a 3250 de 79104
Insertado lote: 3250 a 3500 de 79104
Insertado lote: 3500 a 3750 de 79104
Insertado lote: 3750 a 4000 de 79104
Insertado lote: 4000 a 4250 de 79104
Insertado lote: 4250 a 4500 de 79104
Insertado lote: 4500 a 4750 de 79104
Insertado lote: 4750 a 5000 de 79104
Insertado lote: 5000 a 5250 de 79104
Insertado lote: 5250 a 5500 de 79104
Insertado lote: 5500 a 5750 de 79104
Insertado lote: 5750 a 6000 de 79104
Insertado lote: 6000 a 6250 de 79104
Insertado lote: 6250 a 6500 de 79104
Insertado lote: 6500 a 6750 de 79104
Insertado lote: 6750 a 7000 de 79104
Insertado lote: 7000 a 7250 de 79104
Insertado lote: 7250 a 7500 de 79104
Insertado lote: 7500 a 7750 de 79104
Insertado lote: 7750 a 8000 de 79104
Insertado lote: 8000 a 8250 de 79104
Insertado lote: 8250 a 8500 de 79104
Insertado lote: 8500 a 8750 de 79104
Insertado lote: 8750 a 9000 de 79104
Insertado lote: 9000 a 9250 de 79104
Insertado lote: 9250 a 9500 de 79104
Insertado lote: 9500 a 9750 de 79104
Insertado lote: 9750 a 10000 de 79104
Insertado lote: 10000 a 10250 de 79104
Insertado lote: 10250 a 10500 de 79104
Insertado lote: 10500 a 10750 de 79104
Insertado lote: 10750 a 11000 de 79104
Insertado lote: 11000 a 11250 de 79104
Insertado lote: 11250 a 11500 de 79104
Insertado lote: 11500 a 11750 de 79104
Insertado lote: 11750 a 12000 de 79104
Insertado lote: 12000 a 12250 de 79104
Insertado lote: 12250 a 12500 de 79104
Insertado lote: 12500 a 12750 de 79104
Insertado lote: 12750 a 13000 de 79104
Insertado lote: 13000 a 13250 de 79104
Insertado lote: 13250 a 13500 de 79104
Insertado lote: 13500 a 13750 de 79104
Insertado lote: 13750 a 14000 de 79104
Insertado lote: 14000 a 14250 de 79104
Insertado lote: 14250 a 14500 de 79104
Insertado lote: 14500 a 14750 de 79104
Insertado lote: 14750 a 15000 de 79104
Insertado lote: 15000 a 15250 de 79104
Insertado lote: 15250 a 15500 de 79104
Insertado lote: 15500 a 15750 de 79104
Insertado lote: 15750 a 16000 de 79104
Insertado lote: 16000 a 16250 de 79104
Insertado lote: 16250 a 16500 de 79104
Insertado lote: 16500 a 16750 de 79104
Insertado lote: 16750 a 17000 de 79104
Insertado lote: 17000 a 17250 de 79104
Insertado lote: 17250 a 17500 de 79104
Insertado lote: 17500 a 17750 de 79104
Insertado lote: 17750 a 18000 de 79104
Insertado lote: 18000 a 18250 de 79104
Insertado lote: 18250 a 18500 de 79104
Insertado lote: 18500 a 18750 de 79104
Insertado lote: 18750 a 19000 de 79104
Insertado lote: 19000 a 19250 de 79104
Insertado lote: 19250 a 19500 de 79104
Insertado lote: 19500 a 19750 de 79104
Insertado lote: 19750 a 20000 de 79104
Insertado lote: 20000 a 20250 de 79104
Insertado lote: 20250 a 20500 de 79104
Insertado lote: 20500 a 20750 de 79104
Insertado lote: 20750 a 21000 de 79104
Insertado lote: 21000 a 21250 de 79104
Insertado lote: 21250 a 21500 de 79104
Insertado lote: 21500 a 21750 de 79104
Insertado lote: 21750 a 22000 de 79104
Insertado lote: 22000 a 22250 de 79104
Insertado lote: 22250 a 22500 de 79104
Insertado lote: 22500 a 22750 de 79104
Insertado lote: 22750 a 23000 de 79104
Insertado lote: 23000 a 23250 de 79104
Insertado lote: 23250 a 23500 de 79104
Insertado lote: 23500 a 23750 de 79104
Insertado lote: 23750 a 24000 de 79104
Insertado lote: 24000 a 24250 de 79104
Insertado lote: 24250 a 24500 de 79104
Insertado lote: 24500 a 24750 de 79104
Insertado lote: 24750 a 25000 de 79104
Insertado lote: 25000 a 25250 de 79104
Insertado lote: 25250 a 25500 de 79104
Insertado lote: 25500 a 25750 de 79104
Insertado lote: 25750 a 26000 de 79104
Insertado lote: 26000 a 26250 de 79104
Insertado lote: 26250 a 26500 de 79104
Insertado lote: 26500 a 26750 de 79104
Insertado lote: 26750 a 27000 de 79104
Insertado lote: 27000 a 27250 de 79104
Insertado lote: 27250 a 27500 de 79104
Insertado lote: 27500 a 27750 de 79104
Insertado lote: 27750 a 28000 de 79104
Insertado lote: 28000 a 28250 de 79104
Insertado lote: 28250 a 28500 de 79104
Insertado lote: 28500 a 28750 de 79104
Insertado lote: 28750 a 29000 de 79104
Insertado lote: 29000 a 29250 de 79104
Insertado lote: 29250 a 29500 de 79104
Insertado lote: 29500 a 29750 de 79104
Insertado lote: 29750 a 30000 de 79104
Insertado lote: 30000 a 30250 de 79104
Insertado lote: 30250 a 30500 de 79104
Insertado lote: 30500 a 30750 de 79104
Insertado lote: 30750 a 31000 de 79104
Insertado lote: 31000 a 31250 de 79104
Insertado lote: 31250 a 31500 de 79104
Insertado lote: 31500 a 31750 de 79104
Insertado lote: 31750 a 32000 de 79104
Insertado lote: 32000 a 32250 de 79104
Insertado lote: 32250 a 32500 de 79104
Insertado lote: 32500 a 32750 de 79104
Insertado lote: 32750 a 33000 de 79104
Insertado lote: 33000 a 33250 de 79104
Insertado lote: 33250 a 33500 de 79104
Insertado lote: 33500 a 33750 de 79104
Insertado lote: 33750 a 34000 de 79104
Insertado lote: 34000 a 34250 de 79104
Insertado lote: 34250 a 34500 de 79104
Insertado lote: 34500 a 34750 de 79104
Insertado lote: 34750 a 35000 de 79104
Insertado lote: 35000 a 35250 de 79104
Insertado lote: 35250 a 35500 de 79104
Insertado lote: 35500 a 35750 de 79104
Insertado lote: 35750 a 36000 de 79104
Insertado lote: 36000 a 36250 de 79104
Insertado lote: 36250 a 36500 de 79104
Insertado lote: 36500 a 36750 de 79104
Insertado lote: 36750 a 37000 de 79104
Insertado lote: 37000 a 37250 de 79104
Insertado lote: 37250 a 37500 de 79104
Insertado lote: 37500 a 37750 de 79104
Insertado lote: 37750 a 38000 de 79104
Insertado lote: 38000 a 38250 de 79104
Insertado lote: 38250 a 38500 de 79104
Insertado lote: 38500 a 38750 de 79104
Insertado lote: 38750 a 39000 de 79104
Insertado lote: 39000 a 39250 de 79104
Insertado lote: 39250 a 39500 de 79104
Insertado lote: 39500 a 39750 de 79104
Insertado lote: 39750 a 40000 de 79104
Insertado lote: 40000 a 40250 de 79104
Insertado lote: 40250 a 40500 de 79104
Insertado lote: 40500 a 40750 de 79104
Insertado lote: 40750 a 41000 de 79104
Insertado lote: 41000 a 41250 de 79104
Insertado lote: 41250 a 41500 de 79104
Insertado lote: 41500 a 41750 de 79104
Insertado lote: 41750 a 42000 de 79104
Insertado lote: 42000 a 42250 de 79104
Insertado lote: 42250 a 42500 de 79104
Insertado lote: 42500 a 42750 de 79104
Insertado lote: 42750 a 43000 de 79104
Insertado lote: 43000 a 43250 de 79104
Insertado lote: 43250 a 43500 de 79104
Insertado lote: 43500 a 43750 de 79104
Insertado lote: 43750 a 44000 de 79104
Insertado lote: 44000 a 44250 de 79104
Insertado lote: 44250 a 44500 de 79104
Insertado lote: 44500 a 44750 de 79104
Insertado lote: 44750 a 45000 de 79104
Insertado lote: 45000 a 45250 de 79104
Insertado lote: 45250 a 45500 de 79104
Insertado lote: 45500 a 45750 de 79104
Insertado lote: 45750 a 46000 de 79104
Insertado lote: 46000 a 46250 de 79104
Insertado lote: 46250 a 46500 de 79104
Insertado lote: 46500 a 46750 de 79104
Insertado lote: 46750 a 47000 de 79104
Insertado lote: 47000 a 47250 de 79104
Insertado lote: 47250 a 47500 de 79104
Insertado lote: 47500 a 47750 de 79104
Insertado lote: 47750 a 48000 de 79104
Insertado lote: 48000 a 48250 de 79104
Insertado lote: 48250 a 48500 de 79104
Insertado lote: 48500 a 48750 de 79104
Insertado lote: 48750 a 49000 de 79104
Insertado lote: 49000 a 49250 de 79104
Insertado lote: 49250 a 49500 de 79104
Insertado lote: 49500 a 49750 de 79104
Insertado lote: 49750 a 50000 de 79104
Insertado lote: 50000 a 50250 de 79104
Insertado lote: 50250 a 50500 de 79104
Insertado lote: 50500 a 50750 de 79104
Insertado lote: 50750 a 51000 de 79104
Insertado lote: 51000 a 51250 de 79104
Insertado lote: 51250 a 51500 de 79104
Insertado lote: 51500 a 51750 de 79104
Insertado lote: 51750 a 52000 de 79104
Insertado lote: 52000 a 52250 de 79104
Insertado lote: 52250 a 52500 de 79104
Insertado lote: 52500 a 52750 de 79104
Insertado lote: 52750 a 53000 de 79104
Insertado lote: 53000 a 53250 de 79104
Insertado lote: 53250 a 53500 de 79104
Insertado lote: 53500 a 53750 de 79104
Insertado lote: 53750 a 54000 de 79104
Insertado lote: 54000 a 54250 de 79104
Insertado lote: 54250 a 54500 de 79104
Insertado lote: 54500 a 54750 de 79104
Insertado lote: 54750 a 55000 de 79104
Insertado lote: 55000 a 55250 de 79104
Insertado lote: 55250 a 55500 de 79104
Insertado lote: 55500 a 55750 de 79104
Insertado lote: 55750 a 56000 de 79104
Insertado lote: 56000 a 56250 de 79104
Insertado lote: 56250 a 56500 de 79104
Insertado lote: 56500 a 56750 de 79104
Insertado lote: 56750 a 57000 de 79104
Insertado lote: 57000 a 57250 de 79104
Insertado lote: 57250 a 57500 de 79104
Insertado lote: 57500 a 57750 de 79104
Insertado lote: 57750 a 58000 de 79104
Insertado lote: 58000 a 58250 de 79104
Insertado lote: 58250 a 58500 de 79104
Insertado lote: 58500 a 58750 de 79104
Insertado lote: 58750 a 59000 de 79104
Insertado lote: 59000 a 59250 de 79104
Insertado lote: 59250 a 59500 de 79104
Insertado lote: 59500 a 59750 de 79104
Insertado lote: 59750 a 60000 de 79104
Insertado lote: 60000 a 60250 de 79104
Insertado lote: 60250 a 60500 de 79104
Insertado lote: 60500 a 60750 de 79104
Insertado lote: 60750 a 61000 de 79104
Insertado lote: 61000 a 61250 de 79104
Insertado lote: 61250 a 61500 de 79104
Insertado lote: 61500 a 61750 de 79104
Insertado lote: 61750 a 62000 de 79104
Insertado lote: 62000 a 62250 de 79104
Insertado lote: 62250 a 62500 de 79104
Insertado lote: 62500 a 62750 de 79104
Insertado lote: 62750 a 63000 de 79104
Insertado lote: 63000 a 63250 de 79104
Insertado lote: 63250 a 63500 de 79104
Insertado lote: 63500 a 63750 de 79104
Insertado lote: 63750 a 64000 de 79104
Insertado lote: 64000 a 64250 de 79104
Insertado lote: 64250 a 64500 de 79104
Insertado lote: 64500 a 64750 de 79104
Insertado lote: 64750 a 65000 de 79104
Insertado lote: 65000 a 65250 de 79104
Insertado lote: 65250 a 65500 de 79104
Insertado lote: 65500 a 65750 de 79104
Insertado lote: 65750 a 66000 de 79104
Insertado lote: 66000 a 66250 de 79104
Insertado lote: 66250 a 66500 de 79104
Insertado lote: 66500 a 66750 de 79104
Insertado lote: 66750 a 67000 de 79104
Insertado lote: 67000 a 67250 de 79104
Insertado lote: 67250 a 67500 de 79104
Insertado lote: 67500 a 67750 de 79104
Insertado lote: 67750 a 68000 de 79104
Insertado lote: 68000 a 68250 de 79104
Insertado lote: 68250 a 68500 de 79104
Insertado lote: 68500 a 68750 de 79104
Insertado lote: 68750 a 69000 de 79104
Insertado lote: 69000 a 69250 de 79104
Insertado lote: 69250 a 69500 de 79104
Insertado lote: 69500 a 69750 de 79104
Insertado lote: 69750 a 70000 de 79104
Insertado lote: 70000 a 70250 de 79104
Insertado lote: 70250 a 70500 de 79104
Insertado lote: 70500 a 70750 de 79104
Insertado lote: 70750 a 71000 de 79104
Insertado lote: 71000 a 71250 de 79104
Insertado lote: 71250 a 71500 de 79104
Insertado lote: 71500 a 71750 de 79104
Insertado lote: 71750 a 72000 de 79104
Insertado lote: 72000 a 72250 de 79104
Insertado lote: 72250 a 72500 de 79104
Insertado lote: 72500 a 72750 de 79104
Insertado lote: 72750 a 73000 de 79104
Insertado lote: 73000 a 73250 de 79104
Insertado lote: 73250 a 73500 de 79104
Insertado lote: 73500 a 73750 de 79104
Insertado lote: 73750 a 74000 de 79104
Insertado lote: 74000 a 74250 de 79104
Insertado lote: 74250 a 74500 de 79104
Insertado lote: 74500 a 74750 de 79104
Insertado lote: 74750 a 75000 de 79104
Insertado lote: 75000 a 75250 de 79104
Insertado lote: 75250 a 75500 de 79104
Insertado lote: 75500 a 75750 de 79104
Insertado lote: 75750 a 76000 de 79104
Insertado lote: 76000 a 76250 de 79104
Insertado lote: 76250 a 76500 de 79104
Insertado lote: 76500 a 76750 de 79104
Insertado lote: 76750 a 77000 de 79104
Insertado lote: 77000 a 77250 de 79104
Insertado lote: 77250 a 77500 de 79104
Insertado lote: 77500 a 77750 de 79104
Insertado lote: 77750 a 78000 de 79104
Insertado lote: 78000 a 78250 de 79104
Insertado lote: 78250 a 78500 de 79104
Insertado lote: 78500 a 78750 de 79104
Insertado lote: 78750 a 79000 de 79104
Insertado lote: 79000 a 79104 de 79104

In [27]:
# 4. Función de búsqueda
def chroma_search(query_embedding, k=5):
    raw_res = chroma_coll.query(
        query_embeddings=[query_embedding.tolist()],
        n_results=k
    )
    return raw_res

print("\n--- Resultados de Búsqueda en Chroma ---")
chroma_res = chroma_search(query_embedding, k=5)

# Iteramos sobre la estructura de diccionario que devuelve Chroma
for idx in range(len(chroma_res['ids'][0])):
    print(f"ID: {chroma_res['ids'][0][idx]} | Distancia: {chroma_res['distances'][0][idx]:.4f}")
    print(f"Texto: {chroma_res['documents'][0][idx][:120]}...\n")

--- Resultados de Búsqueda en Chroma ---
ID: 10176 | Distancia: 0.2593
Texto: Battery tester A battery tester is an electronic device intended for testing the state of an electric battery, going fro...

ID: 1 | Distancia: 0.2764
Texto: Battery indicator A battery indicator (also known as a battery gauge) is a device which gives information about a batter...

ID: 10177 | Distancia: 0.3198
Texto: ing procedure, according to the type of battery being tested, such as the â€œ421â€ test for lead-acid vehicle batteries...

ID: 37406 | Distancia: 0.3217
Texto: ils. One was connected via a series resistor to the battery supply. The second was connected to the same battery supply ...

ID: 71872 | Distancia: 0.3228
Texto: is achieved. Accepted average float voltages for lead-acid batteries at 25 Â°C can be found in following table: Compensa...

**¿Qué tan fácil fue implementar todo comparado con Qdrant/Milvus?**   
Fue sumamente sencillo. Chroma reduce muchísimo el código duplicado y el boilerplate. No requiere definir configuraciones de red, ni tipados estrictos de payload, e inserta listas nativas directamente sin mapeos complejos. Es ideal para cuadernos de Jupyter.

**¿Qué limitaciones ves para un sistema en producción?**   
Al estar tan simplificado, carece de controles avanzados para Sharding (fragmentación de datos en varios servidores), replicación activa, tolerancia a fallos a gran escala o gestión fina de la memoria RAM. Guardar millones de vectores pesados en Chroma puede degradar el rendimiento drásticamente en comparación con un clúster dedicado de Milvus o Qdrant.

## Parte 7 — SQL + vectores: PostgreSQL/pgvector (vector search transparente)

### Objetivo
Guardar embeddings en una tabla y ejecutar una consulta SQL de similitud.

### Qué debes implementar
1. Conectar a una base PostgreSQL con `pgvector` habilitado.
2. Crear una tabla (ej. `documents`) con:
   - `id` (PK)
   - `text` (texto)
   - `embedding` (vector(D))
   - metadata (columnas adicionales)
3. Insertar todos los documentos y embeddings.
4. Consultar Top-k por similitud, ordenando por distancia.

### Fórmula conceptual (lo que implementa tu SQL)
Para una consulta `q`, buscas:
$$ argmin_d \in D \; \text{dist}(\vec{q}, \vec{d})$$
donde `dist` puede ser L2 o una variante para cosine (según configuración).

### Entregable
- Función `pgvector_search(query_embedding, k)` que ejecute SQL y devuelva:
  - id, score/distancia, text, metadata

### Preguntas
- ¿Qué tan “explicable” te parece esta aproximación vs las otras?
- ¿Qué ventajas ofrece el mundo SQL (JOIN, filtros, agregaciones)?
- ¿Qué limitaciones esperas en escalabilidad frente a bases vectoriales dedicadas?

In [28]:
import sqlite3
import json

# 1. Conectamos a una base de datos SQLite en memoria
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# 2. Creamos la tabla imitando la estructura de pgvector
cursor.execute("""
CREATE TABLE documents (
    id INTEGER PRIMARY KEY,
    text TEXT,
    embedding TEXT, -- Guardaremos el vector como un string JSON por limitaciones de SQLite
    doc_id INTEGER
)
""")

# 3. Insertamos los documentos y embeddings
for idx, row in chunks_df.iterrows():
    cursor.execute(
        "INSERT INTO documents (id, text, embedding, doc_id) VALUES (?, ?, ?, ?)",
        (int(idx), row["text"], json.dumps(embeddings[idx].tolist()), int(row["doc_id"]))
    )
conn.commit()

# Implementamos la fórmula conceptual: Distancia Coseno vía Python para inyectar en SQL
def cosine_distance_sql(query_str, current_vector_str):
    q = np.array(json.loads(query_str))
    v = np.array(json.loads(current_vector_str))
    # Distancia Coseno = 1 - (Producto punto / (norma_q * norma_v))
    # Como ya están normalizados, solo es 1 - producto_punto
    return float(1.0 - np.dot(q, v))

# Registramos la función en SQLite para poder usarla dentro de los Queries de SQL
conn.create_function("COSINE_DISTANCE", 2, cosine_distance_sql)

# 4. Función de búsqueda simulando el Query de pgvector
def pgvector_search(query_embedding, k=5):
    query_json = json.dumps(query_embedding.tolist())

    # Esta consulta es idéntica conceptualmente al: SELECT * FROM documents ORDER BY embedding <=> vec LIMIT k; de pgvector
    cursor.execute("""
        SELECT id, COSINE_DISTANCE(?, embedding) as distancia, text, doc_id
        FROM documents
        ORDER BY distancia ASC
        LIMIT ?
    """, (query_json, k))

    rows = cursor.fetchall()
    results = []
    for r in rows:
        results.append((r[0], r[1], r[2], {"doc_id": r[3]}))
    return results

print("\n--- Resultados de Búsqueda simulando pgvector (SQL) ---")
sql_res = pgvector_search(query_embedding, k=5)
for res in sql_res:
    print(f"ID (PK): {res[0]} | Distancia Calculada por SQL: {res[1]:.4f}")
    print(f"Texto: {res[2][:120]}...\n")

conn.close()

--- Resultados de Búsqueda simulando pgvector (SQL) ---
ID (PK): 10176 | Distancia Calculada por SQL: 0.1297
Texto: Battery tester A battery tester is an electronic device intended for testing the state of an electric battery, going fro...

ID (PK): 1 | Distancia Calculada por SQL: 0.1382
Texto: Battery indicator A battery indicator (also known as a battery gauge) is a device which gives information about a batter...

ID (PK): 10177 | Distancia Calculada por SQL: 0.1599
Texto: ing procedure, according to the type of battery being tested, such as the â€œ421â€ test for lead-acid vehicle batteries...

ID (PK): 37406 | Distancia Calculada por SQL: 0.1609
Texto: ils. One was connected via a series resistor to the battery supply. The second was connected to the same battery supply ...

ID (PK): 71872 | Distancia Calculada por SQL: 0.1614
Texto: is achieved. Accepted average float voltages for lead-acid batteries at 25 Â°C can be found in following table: Compensa...

**¿Qué tan “explicable” te parece esta aproximación vs las otras?**  
Es la más transparente de todas por lejos. Cualquier desarrollador de software entiende un SELECT ... FROM ... ORDER BY distancia LIMIT k. No hay cajas negras de librerías externas ni APIs raras; es pura álgebra lineal aplicada sobre un motor relacional que ya conocemos.

**¿Qué ventajas ofrece el mundo SQL (JOIN, filtros, agregaciones)?**   
La ventaja es masiva. Te permite cruzar tus datos vectoriales semánticos con transacciones operacionales usando un JOIN tradicional instantáneamente (ej. buscar reviews similares de películas, pero filtrando únicamente los usuarios que tienen una membresía activa y compraron en la última semana). Todo en una sola consulta ACID robusta.

**¿Qué limitaciones esperas en escalabilidad frente a bases vectoriales dedicadas?**  
SQL no fue diseñado originalmente para buscar en espacios multidimensionales de alta densidad. Hacer un escaneo completo (Full Table Scan) calculando distancias vectoriales para millones de filas en cada query bloquea la base de datos por completo. Aunque pgvector tiene índices como IVFFlat o HNSW, las bases dedicadas (como Qdrant o Milvus) distribuyen el cómputo y manejan la memoria de una forma infinitamente más eficiente para cargas masivas de Big Data.